// Code generated by go-mockgen 1.3.4; DO NOT EDIT.

package mocks

import (
	"context"
	"sync"

	recipes "github.com/rubengomes8/HappyMouthBackend/internal/recipes"
)

// MockService is a mock implementation of the service interface (from the
// package github.com/rubengomes8/HappyMouthBackend/internal/recipes) used
// for unit testing.
type MockService struct {
	// AskRecipeFunc is an instance of a mock function object controlling
	// the behavior of the method AskRecipe.
	AskRecipeFunc *ServiceAskRecipeFunc
	// GetRecipesByUserFunc is an instance of a mock function object
	// controlling the behavior of the method GetRecipesByUser.
	GetRecipesByUserFunc *ServiceGetRecipesByUserFunc
	// SetUserRecipeFavoriteFunc is an instance of a mock function object
	// controlling the behavior of the method SetUserRecipeFavorite.
	SetUserRecipeFavoriteFunc *ServiceSetUserRecipeFavoriteFunc
}

// NewMockService creates a new mock of the service interface. All methods
// return zero values for all results, unless overwritten.
func NewMockService() *MockService {
	return &MockService{
		AskRecipeFunc: &ServiceAskRecipeFunc{
			defaultHook: func(context.Context, recipes.RecipeDefinitions, int) (r0 recipes.Recipe, r1 error) {
				return
			},
		},
		GetRecipesByUserFunc: &ServiceGetRecipesByUserFunc{
			defaultHook: func(context.Context, int) (r0 []recipes.Recipe, r1 error) {
				return
			},
		},
		SetUserRecipeFavoriteFunc: &ServiceSetUserRecipeFavoriteFunc{
			defaultHook: func(context.Context, int, string, bool) (r0 error) {
				return
			},
		},
	}
}

// NewStrictMockService creates a new mock of the service interface. All
// methods panic on invocation, unless overwritten.
func NewStrictMockService() *MockService {
	return &MockService{
		AskRecipeFunc: &ServiceAskRecipeFunc{
			defaultHook: func(context.Context, recipes.RecipeDefinitions, int) (recipes.Recipe, error) {
				panic("unexpected invocation of MockService.AskRecipe")
			},
		},
		GetRecipesByUserFunc: &ServiceGetRecipesByUserFunc{
			defaultHook: func(context.Context, int) ([]recipes.Recipe, error) {
				panic("unexpected invocation of MockService.GetRecipesByUser")
			},
		},
		SetUserRecipeFavoriteFunc: &ServiceSetUserRecipeFavoriteFunc{
			defaultHook: func(context.Context, int, string, bool) error {
				panic("unexpected invocation of MockService.SetUserRecipeFavorite")
			},
		},
	}
}

// surrogateMockService is a copy of the service interface (from the package
// github.com/rubengomes8/HappyMouthBackend/internal/recipes). It is
// redefined here as it is unexported in the source package.
type surrogateMockService interface {
	AskRecipe(context.Context, recipes.RecipeDefinitions, int) (recipes.Recipe, error)
	GetRecipesByUser(context.Context, int) ([]recipes.Recipe, error)
	SetUserRecipeFavorite(context.Context, int, string, bool) error
}

// NewMockServiceFrom creates a new mock of the MockService interface. All
// methods delegate to the given implementation, unless overwritten.
func NewMockServiceFrom(i surrogateMockService) *MockService {
	return &MockService{
		AskRecipeFunc: &ServiceAskRecipeFunc{
			defaultHook: i.AskRecipe,
		},
		GetRecipesByUserFunc: &ServiceGetRecipesByUserFunc{
			defaultHook: i.GetRecipesByUser,
		},
		SetUserRecipeFavoriteFunc: &ServiceSetUserRecipeFavoriteFunc{
			defaultHook: i.SetUserRecipeFavorite,
		},
	}
}

// ServiceAskRecipeFunc describes the behavior when the AskRecipe method of
// the parent MockService instance is invoked.
type ServiceAskRecipeFunc struct {
	defaultHook func(context.Context, recipes.RecipeDefinitions, int) (recipes.Recipe, error)
	hooks       []func(context.Context, recipes.RecipeDefinitions, int) (recipes.Recipe, error)
	history     []ServiceAskRecipeFuncCall
	mutex       sync.Mutex
}

// AskRecipe delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockService) AskRecipe(v0 context.Context, v1 recipes.RecipeDefinitions, v2 int) (recipes.Recipe, error) {
	r0, r1 := m.AskRecipeFunc.nextHook()(v0, v1, v2)
	m.AskRecipeFunc.appendCall(ServiceAskRecipeFuncCall{v0, v1, v2, r0, r1})
	return r0, r1
}

// SetDefaultHook sets function that is called when the AskRecipe method of
// the parent MockService instance is invoked and the hook queue is empty.
func (f *ServiceAskRecipeFunc) SetDefaultHook(hook func(context.Context, recipes.RecipeDefinitions, int) (recipes.Recipe, error)) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// AskRecipe method of the parent MockService instance invokes the hook at
// the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *ServiceAskRecipeFunc) PushHook(hook func(context.Context, recipes.RecipeDefinitions, int) (recipes.Recipe, error)) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *ServiceAskRecipeFunc) SetDefaultReturn(r0 recipes.Recipe, r1 error) {
	f.SetDefaultHook(func(context.Context, recipes.RecipeDefinitions, int) (recipes.Recipe, error) {
		return r0, r1
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *ServiceAskRecipeFunc) PushReturn(r0 recipes.Recipe, r1 error) {
	f.PushHook(func(context.Context, recipes.RecipeDefinitions, int) (recipes.Recipe, error) {
		return r0, r1
	})
}

func (f *ServiceAskRecipeFunc) nextHook() func(context.Context, recipes.RecipeDefinitions, int) (recipes.Recipe, error) {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *ServiceAskRecipeFunc) appendCall(r0 ServiceAskRecipeFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of ServiceAskRecipeFuncCall objects describing
// the invocations of this function.
func (f *ServiceAskRecipeFunc) History() []ServiceAskRecipeFuncCall {
	f.mutex.Lock()
	history := make([]ServiceAskRecipeFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// ServiceAskRecipeFuncCall is an object that describes an invocation of
// method AskRecipe on an instance of MockService.
type ServiceAskRecipeFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 context.Context
	// Arg1 is the value of the 2nd argument passed to this method
	// invocation.
	Arg1 recipes.RecipeDefinitions
	// Arg2 is the value of the 3rd argument passed to this method
	// invocation.
	Arg2 int
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 recipes.Recipe
	// Result1 is the value of the 2nd result returned from this method
	// invocation.
	Result1 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c ServiceAskRecipeFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0, c.Arg1, c.Arg2}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c ServiceAskRecipeFuncCall) Results() []interface{} {
	return []interface{}{c.Result0, c.Result1}
}

// ServiceGetRecipesByUserFunc describes the behavior when the
// GetRecipesByUser method of the parent MockService instance is invoked.
type ServiceGetRecipesByUserFunc struct {
	defaultHook func(context.Context, int) ([]recipes.Recipe, error)
	hooks       []func(context.Context, int) ([]recipes.Recipe, error)
	history     []ServiceGetRecipesByUserFuncCall
	mutex       sync.Mutex
}

// GetRecipesByUser delegates to the next hook function in the queue and
// stores the parameter and result values of this invocation.
func (m *MockService) GetRecipesByUser(v0 context.Context, v1 int) ([]recipes.Recipe, error) {
	r0, r1 := m.GetRecipesByUserFunc.nextHook()(v0, v1)
	m.GetRecipesByUserFunc.appendCall(ServiceGetRecipesByUserFuncCall{v0, v1, r0, r1})
	return r0, r1
}

// SetDefaultHook sets function that is called when the GetRecipesByUser
// method of the parent MockService instance is invoked and the hook queue
// is empty.
func (f *ServiceGetRecipesByUserFunc) SetDefaultHook(hook func(context.Context, int) ([]recipes.Recipe, error)) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// GetRecipesByUser method of the parent MockService instance invokes the
// hook at the front of the queue and discards it. After the queue is empty,
// the default hook function is invoked for any future action.
func (f *ServiceGetRecipesByUserFunc) PushHook(hook func(context.Context, int) ([]recipes.Recipe, error)) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *ServiceGetRecipesByUserFunc) SetDefaultReturn(r0 []recipes.Recipe, r1 error) {
	f.SetDefaultHook(func(context.Context, int) ([]recipes.Recipe, error) {
		return r0, r1
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *ServiceGetRecipesByUserFunc) PushReturn(r0 []recipes.Recipe, r1 error) {
	f.PushHook(func(context.Context, int) ([]recipes.Recipe, error) {
		return r0, r1
	})
}

func (f *ServiceGetRecipesByUserFunc) nextHook() func(context.Context, int) ([]recipes.Recipe, error) {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *ServiceGetRecipesByUserFunc) appendCall(r0 ServiceGetRecipesByUserFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of ServiceGetRecipesByUserFuncCall objects
// describing the invocations of this function.
func (f *ServiceGetRecipesByUserFunc) History() []ServiceGetRecipesByUserFuncCall {
	f.mutex.Lock()
	history := make([]ServiceGetRecipesByUserFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// ServiceGetRecipesByUserFuncCall is an object that describes an invocation
// of method GetRecipesByUser on an instance of MockService.
type ServiceGetRecipesByUserFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 context.Context
	// Arg1 is the value of the 2nd argument passed to this method
	// invocation.
	Arg1 int
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 []recipes.Recipe
	// Result1 is the value of the 2nd result returned from this method
	// invocation.
	Result1 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c ServiceGetRecipesByUserFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0, c.Arg1}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c ServiceGetRecipesByUserFuncCall) Results() []interface{} {
	return []interface{}{c.Result0, c.Result1}
}

// ServiceSetUserRecipeFavoriteFunc describes the behavior when the
// SetUserRecipeFavorite method of the parent MockService instance is
// invoked.
type ServiceSetUserRecipeFavoriteFunc struct {
	defaultHook func(context.Context, int, string, bool) error
	hooks       []func(context.Context, int, string, bool) error
	history     []ServiceSetUserRecipeFavoriteFuncCall
	mutex       sync.Mutex
}

// SetUserRecipeFavorite delegates to the next hook function in the queue
// and stores the parameter and result values of this invocation.
func (m *MockService) SetUserRecipeFavorite(v0 context.Context, v1 int, v2 string, v3 bool) error {
	r0 := m.SetUserRecipeFavoriteFunc.nextHook()(v0, v1, v2, v3)
	m.SetUserRecipeFavoriteFunc.appendCall(ServiceSetUserRecipeFavoriteFuncCall{v0, v1, v2, v3, r0})
	return r0
}

// SetDefaultHook sets function that is called when the
// SetUserRecipeFavorite method of the parent MockService instance is
// invoked and the hook queue is empty.
func (f *ServiceSetUserRecipeFavoriteFunc) SetDefaultHook(hook func(context.Context, int, string, bool) error) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// SetUserRecipeFavorite method of the parent MockService instance invokes
// the hook at the front of the queue and discards it. After the queue is
// empty, the default hook function is invoked for any future action.
func (f *ServiceSetUserRecipeFavoriteFunc) PushHook(hook func(context.Context, int, string, bool) error) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *ServiceSetUserRecipeFavoriteFunc) SetDefaultReturn(r0 error) {
	f.SetDefaultHook(func(context.Context, int, string, bool) error {
		return r0
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *ServiceSetUserRecipeFavoriteFunc) PushReturn(r0 error) {
	f.PushHook(func(context.Context, int, string, bool) error {
		return r0
	})
}

func (f *ServiceSetUserRecipeFavoriteFunc) nextHook() func(context.Context, int, string, bool) error {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *ServiceSetUserRecipeFavoriteFunc) appendCall(r0 ServiceSetUserRecipeFavoriteFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of ServiceSetUserRecipeFavoriteFuncCall
// objects describing the invocations of this function.
func (f *ServiceSetUserRecipeFavoriteFunc) History() []ServiceSetUserRecipeFavoriteFuncCall {
	f.mutex.Lock()
	history := make([]ServiceSetUserRecipeFavoriteFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// ServiceSetUserRecipeFavoriteFuncCall is an object that describes an
// invocation of method SetUserRecipeFavorite on an instance of MockService.
type ServiceSetUserRecipeFavoriteFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 context.Context
	// Arg1 is the value of the 2nd argument passed to this method
	// invocation.
	Arg1 int
	// Arg2 is the value of the 3rd argument passed to this method
	// invocation.
	Arg2 string
	// Arg3 is the value of the 4th argument passed to this method
	// invocation.
	Arg3 bool
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c ServiceSetUserRecipeFavoriteFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0, c.Arg1, c.Arg2, c.Arg3}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c ServiceSetUserRecipeFavoriteFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}
