definitions:
  github.com_rubengomes8_HappyMouthBackend_internal_ingredients.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  github.com_rubengomes8_HappyMouthBackend_internal_ingredients.Ingredient:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  github.com_rubengomes8_HappyMouthBackend_internal_recipes.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  github.com_rubengomes8_HappyMouthBackend_internal_recipes.Recipe:
    properties:
      calories:
        type: number
      created_at:
        type: string
      definitions:
        $ref: '#/definitions/github.com_rubengomes8_HappyMouthBackend_internal_recipes.RecipeDefinitions'
      deleted_at:
        type: string
      id:
        type: string
      ingredients:
        items:
          type: string
        type: array
      instructions:
        items:
          type: string
        type: array
      is_favorite:
        type: boolean
      title:
        type: string
      updated_at:
        type: string
    type: object
  github.com_rubengomes8_HappyMouthBackend_internal_recipes.RecipeDefinitions:
    properties:
      exclude_ingredients:
        items:
          type: string
        type: array
      include_ingredients:
        items:
          type: string
        type: array
      recipe_type:
        $ref: '#/definitions/github.com_rubengomes8_HappyMouthBackend_internal_recipes.RecipeType'
    type: object
  github.com_rubengomes8_HappyMouthBackend_internal_recipes.RecipeType:
    properties:
      id:
        type: integer
      type:
        type: integer
    type: object
  github.com_rubengomes8_HappyMouthBackend_internal_users.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  github.com_rubengomes8_HappyMouthBackend_internal_users.UserCoins:
    properties:
      coins:
        type: integer
      user_id:
        type: integer
    type: object
  internal_ingredients.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  internal_ingredients.Ingredient:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  internal_recipes.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  internal_recipes.Recipe:
    properties:
      calories:
        type: number
      created_at:
        type: string
      definitions:
        $ref: '#/definitions/internal_recipes.RecipeDefinitions'
      deleted_at:
        type: string
      id:
        type: string
      ingredients:
        items:
          type: string
        type: array
      instructions:
        items:
          type: string
        type: array
      is_favorite:
        type: boolean
      title:
        type: string
      updated_at:
        type: string
    type: object
  internal_recipes.RecipeDefinitions:
    properties:
      exclude_ingredients:
        items:
          type: string
        type: array
      include_ingredients:
        items:
          type: string
        type: array
      recipe_type:
        $ref: '#/definitions/internal_recipes.RecipeType'
    type: object
  internal_recipes.RecipeType:
    properties:
      id:
        type: integer
      type:
        type: integer
    type: object
  internal_users.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  internal_users.UserCoins:
    properties:
      coins:
        type: integer
      user_id:
        type: integer
    type: object
info:
  contact: {}
paths:
  /v1/ingredients:
    get:
      consumes:
      - application/json
      description: Gets a list of ingredients.
      parameters:
      - description: Sort ingredients by name.
        in: query
        name: sort-by-name
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github.com_rubengomes8_HappyMouthBackend_internal_ingredients.Ingredient'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github.com_rubengomes8_HappyMouthBackend_internal_ingredients.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github.com_rubengomes8_HappyMouthBackend_internal_ingredients.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Gets a list of ingredients.
      tags:
      - ingredients
  /v1/recipes:
    get:
      consumes:
      - application/json
      description: Gets a list of recipes based on the provided filter
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github.com_rubengomes8_HappyMouthBackend_internal_recipes.Recipe'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github.com_rubengomes8_HappyMouthBackend_internal_recipes.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github.com_rubengomes8_HappyMouthBackend_internal_recipes.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Gets a list of recipes based on the provided filters.
      tags:
      - Recipes
    post:
      consumes:
      - application/json
      description: Generates a new recipe using OpenAI if it is a new set of parameters.
      parameters:
      - description: Generate recipe request.
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github.com_rubengomes8_HappyMouthBackend_internal_recipes.RecipeDefinitions'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github.com_rubengomes8_HappyMouthBackend_internal_recipes.Recipe'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github.com_rubengomes8_HappyMouthBackend_internal_recipes.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github.com_rubengomes8_HappyMouthBackend_internal_recipes.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Generates a new recipe using OpenAI if it is a new set of parameters.
      tags:
      - Recipes
  /v1/recipes/{id}/favorite:
    patch:
      consumes:
      - application/json
      description: Updates the favorite state of a user recipe.
      parameters:
      - description: Update user recipe favorite request.
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github.com_rubengomes8_HappyMouthBackend_internal_recipes.RecipeDefinitions'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github.com_rubengomes8_HappyMouthBackend_internal_recipes.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github.com_rubengomes8_HappyMouthBackend_internal_recipes.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Updates the favorite state of a user recipe.
      tags:
      - Recipes
  /v1/users/coins:
    get:
      consumes:
      - application/json
      description: Gets the number of user coins.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_users.UserCoins'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_users.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_users.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Gets the number of user coins.
      tags:
      - users
swagger: "2.0"
